### PR TITLE
Wpf control

### PR DESCRIPTION
**Pull request by shakram02**
Created a sample for the wpf user control just access the camera control object from the CameraControlWpf object

### CODE REVIEW

**Comment by free5lot** [comment]
Thank you @shakram02, it's appreciated!
As I understand the PR#2 should be ignored by me, shouldn't it? 

About this PR#3, it's great, I'll take a look and will merge it to the project, but I'll get a PC only in a week. Thanks!

**Comment by free5lot** [comment]
About an issue you have in Dispose() of DsROTEntry when you press close button of WPF sample - I think something's wrong with your code. Do you have this exception in Winforms samples? Further investigation is required, including the type and Message of the exception to fix it.

The thing is that DirectShowLib is an external (and not mine) project, so no modifications to it will be accepted. So it's desired to fix all problems on our end, in Camera_Net project.

**Comment by shakram02** [comment]
No, I don't get it on the winForms project, I guess it can be easily solved on our side by just swallowing this exception ( as the app is already closing anyway ) but I was wondering about its true reason ( just for the sake of curiosity ) 
about PR#2 yes, I didn't test the control, then and I should've done first, I falsely thought the control doesn't get resized so I closed it, nothing important about it

**Comment by free5lot** [comment]
For now and further week I have no computer with VisualStudio, so I can advise you to catch the Exception ex, and get its type and Message property, the problem can become obvious.

**Comment by shakram02** [comment]
The exception is as follows
value of m_cookie 65536
value of _HResult -2147024809 ( a private field in the exception object )
Value does not fall within the expected range.

Stack trace
   at System.Runtime.InteropServices.ComTypes.IRunningObjectTable.Revoke(Int32 dwRegister)
   at DirectShowLib.DsROTEntry.Dispose()

**Comment by free5lot** [comment]
Hi there! I looked deeply in you commits. I can't directly accept your PR as there are some issues in commits, I had to make a lot of different small changes. Also you should not include in commits any binaries as they can have big file size and most importantly will be created different every build.

About the exception you were facing and fixed in DirectShowLib (not a correct way). I found out that you missed closing code from my original VerySimple sample when you were coping the code. I added the CloseCamera() call on OnClose event and it was working as expected without exceptions.

I fixed the exception with correct program close process, changed .Net Framework profile to match others, removed some useless references and etc and added it to the library, thank you, I also added you to commits messages.

**Pull request closed without merging**
